MALWARE_NAMES = [
    "Keitaro",
    "Tactical RMM",
    "Gophish",
    "Acunetix",
    "ARL",
    "Burp Collaborator",
    "Mozi",
    "Interactsh",
    "Cobalt Strike",
    "Hajime",
    "Cobalt Strike Unverified",
    "Pyramid C2",
    "Metasploit",
    "Mirai",
    "AsyncRAT",
    "Ramnit",
    "Sliver",
    "evilgophish",
    "reNgine",
    "Nessus VA",
    "Havoc",
    "Viper",
    "Supershell",
    "Lumma",
    "Quasar",
    "Mythic",
    "Remcos",
    "Gh0st RAT",
    "ReverseSSH",
    "Metasploit Meterpreter",
    "MITRE Caldera",
    "Hak5 Cloud C2",
    "Redline Stealer",
    "AdaptixC2",
    "Ligolo-ng",
    "DcRat",
    "Latrodectus",
    "DayBreak",
    "XenoRAT",
    "L3MON",
    "Daam",
    "Kaiji",
    "VenomRAT",
    "Chaos RAT",
    "ValleyRAT",
    "Burp Suite",
    "Yakit Security Tool",
    "RedWarden",
    "ShadowPad",
    "OWASP ZAP API",
    "SparkRAT",
    "DarkComet",
    "Moobot",
    "HOOKBOT",
    "Unam",
    "GobRAT",
    "ClayRat",
    "qakbot",
    "Pupy C2",
    "Stealc",
    "Starkiller",
    "X-Ray Vuln Scanner",
    "SectopRAT",
    "SpiceRAT",
    "Brute Ratel C4",
    "Lazarus Group",
    "Kimsuky",
    "Ares",
    "Lazarus Stealer",
    "Covenant",
    "RedJuliett",
    "JS-Tap",
    "HOOKBOT Fork",
    "Chalubo RAT",
]
MALWARE_SUBSYSTEMS = [
    "C2",
    "Exploit Server",
    "Infrastructure",
    "Management",
    "Phishing",
    "Red Team Tools",
    "Redirect",
    "Team Server",
    "Victim",
]
